std = "23"
compiler_flags = ""

includes = [
  "*.h",
  "*.hpp",
]

sources = [
  "*.cpp",
  "*.cc",
]

deps = [
  "github.com/dagobert-duck/somelib/money",
  "github.com/megakuul/bob/@external:gtkmm-4.0",
  "github.com/megakuul/bob/@external:z",
]